[target.aarch64-unknown-linux-gnu]
dockerfile = "cross/aarch64.Dockerfile"

[target.aarch64-unknown-linux-gnu.env]
passthrough = ["OPENSSL_INCLUDE_DIR=/usr/include/aarch64-linux-gnu", "OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu"]
